name: bot approval

on:
  issue_comment:
    types:
      - created

jobs:
  taas_approval:
    # runs-on: [ "self-hosted", "datalake-nonprod-maven11-runner" ]
    runs-on: "ubuntu-latest"
    if: |
      github.event.issue.pull_request
       && github.event.issue.state == 'open'
       && contains(fromJson('["thesuperzapper", "xxxxxx"]'), github.event.comment.user.login)
       && contains(github.event.comment.body, '/taas-approval')
    steps:
      - name: Get PR Details
        uses: actions/github-script@v6
        id: get-pr
        with:
          retries: 3
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            }

            core.info(`Attempting to get PR #${request.pull_number} from ${request.owner}/${request.repo}...`)
            try {
              const result = await github.rest.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Post Rejection Comment (not in mergeable state)
        uses: actions/github-script@v6
        if: fromJSON(steps.get-pr.outputs.result).mergeable == false
        with:
          retries: 3
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@${{ github.event.comment.user.login }}, this PR is not in a mergeable state.',
            }
            
            core.info(`Attempting to post comment on PR #${request.issue_number}...`)
            try {
              const result = await github.rest.issues.createComment(request)
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ fromJSON(steps.get-pr.outputs.result).merge_commit_sha }}
#          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Check which files changed
        uses: tj-actions/changed-files@v34
        id: changed-files
        if: fromJSON(steps.get-pr.outputs.result).mergeable == true
        with:
          sha: ${{ fromJSON(steps.get-pr.outputs.result).merge_commit_sha }}
          base_sha: ${{ fromJSON(steps.get-pr.outputs.result).base.sha }}
          files: |
            /datalake-nonprod-1/*/taas/source.properties
            /datalake-prod-1/*/taas/source.properties

      - name: Post Rejection Comment (wrong files changed)
        uses: actions/github-script@v6
        if: |
          fromJSON(steps.get-pr.outputs.result).mergeable == true
           && steps.changed-files.outputs.only_modified != 'true'
        with:
          retries: 3
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: [
                '@${{ github.event.comment.user.login }}, this PR is not eligible for bot-approval.',
                '', 
                'To be eligible, the PR must only modify files matching:',
                ' - `/datalake-nonprod-1/*/taas/source.properties`',
                ' - `/datalake-prod-1/*/taas/source.properties`'
              ].join('\n'),
            }
            
            core.info(`Attempting to post comment on PR #${request.issue_number}...`)
            try {
              const result = await github.rest.issues.createComment(request)
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Approve PR
        uses: actions/github-script@v6
        if: |
          fromJSON(steps.get-pr.outputs.result).mergeable == true
           && steps.changed-files.outputs.only_modified == 'true'
        with:
          retries: 3
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              commit_id: '${{ fromJSON(steps.get-pr.outputs.result).head.sha }}',
              event: 'APPROVE',
            }

            core.info(`Attempting to approve PR #${request.pull_number} @ ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}...`)
            try {
              const result = await github.rest.pulls.createReview(request)
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
